### ISSUE TITLE
Is it possible to fix the position of a LateXMathSkin?

### ISSUE THREAD

**Issue by spockoyno** [bitstormGER/jlatexmathfx#5]
When the parent panel of a LateX control is resized, the control's position relative to other widgets changes (and the look of the GUI is corrupted). This is due to the implementation of the "computePrefHeight(...)" and "computePrefWidth(...)" in the LateXMathSkin class. Is it possible to also provide an option to fix the position of a LateX control?

**Comment by bitstormFA** [comment]
should be fixed in 0.33

**Comment by spockoyno** [comment]
@bitstormGER Thank you for the new release and for incorporating my suggestions!

I'm afraid the current issue still remains. I probably didn't explain it properly - my fault. Below are the pictures.

There're  3 VBoxes, each with latex controls. Resizing the panel distorts the relative positions of the displays (especially in large GUIs with many panels.) The desired view obtains, eg, by replacing the last line, in 'LateXMathSkin', of 
` protected double computePrefHeight(...) {
   ...
        return topInset + bottomInset + teXIcon.getIconHeight() * size;
    }
`
with 
`return rightInset + leftInset + teXIcon.getIconWidth() + iconWidthDelta`, where `iconWidthDelta >=0`

The problem is that `teXIcon` is private. So could it be helpful to add  `protected double getIconHeight()` and `getIconWidth()` to 'LateXMathSkin' to allow subclass implementations?

Desired view: 

<img width="602" alt="screen shot 2017-11-14 at 15 44 43" src="https://user-images.githubusercontent.com/18262815/32788824-2bdf78e0-c952-11e7-8fad-0bef65eaab2b.png">

Current implementation: 
<img width="596" alt="screen shot 2017-11-14 at 15 48 42" src="https://user-images.githubusercontent.com/18262815/32788950-7b82602e-c952-11e7-8db9-c60f83282a17.png">
